---
title: <center> "TBD"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---
## Intro

### Assessing trends in adult vaccination: the flu vaccine  
#### A project exploring the relationship between quantitative and qualitative analysis

Welcome to our p8105 final project. We (Adam, Maria, Ronaé) looked at data concerning flu vaccines, the people who choose to get them and who choose not to get them, and how they feel about vaccines from their candid expressions.  We started this project during a tumultuous year, when a COVID-19 vaccine seemed nearly impossible and wearing a mask was a radical gesture in some areas.  Coming from different departments, we consider this to be a mixed methods approach to data science.  The data provided some interesting findings, and our website highlights some of those for you. We believe that adult immunizations are important, and it’s engagement will push us towards achieving health equity for all. 

All the best,

*Adam, Maria, Ronaé*

## Project inspiration

<center>
<iframe width="840" height="472" src="https://www.youtubetrimmer.com/view/?v=qAWtUu88ug4&start=305&end=343" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>


A few weeks ago, our team member Maria gave herself the equivalent of a paper cut with a metal coffee can. Remembering an episode of Arthur (the aardvark) from childhood, in which Arthur cut himself on a lima bean can and required a tetanus shot, she decided to look up her immunization record and found that her last Tdap immunization occurred more than 10 years ago. This anecdote helped us realize: what kind of vaccine schedule are adults on, if any at all? How many individuals know that the tetanus vaccine should be received every ten years? How can we ensure that adults know the proper vaccination schedule in order to ensure maximum health benefit not only for themselves, but for the sake of public health? Our reckoning with immunization schedules leads us to think about the current flu season, guiding us to do a deep dive concerning the influenza vaccine. 

Recently, there has been much attention guided towards vaccinations and immunizations. Will there be a COVID-19 vaccine in the near future? Should vaccinations be required for children to attend school?  How accessible are facilities that offer vaccines and what are the demographics underlying those who are vaccinated?  Before we can predict the future of vaccinations, especially participation in receiving doses, it is important to explore current data about available vaccines.  More than ever, we are reminded about the gravity of communicable diseases and how they can completely influence local and international communities.  A significant portion of immunizations is focused on children, but what about the adult population? Adult immunization is just as important, but consistently misses the limelight.  This project will explore data that contains information regarding flu vaccines, accessibility to obtain the vaccines, and the consequences of not participating in immunization.


