---
title: <center> "Methods"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---


###	Methods

###	Sources of data

**National Health Survey**

The National Health Interview Survey (NHIS) is one of the major data collection programs of the National Center for Health Statistics (NCHS) which is part of the Centers for Disease Control and Prevention (CDC). While the NHIS has been conducted continuously since 1957, the content of the survey has been updated about every 15-20 years to incorporate advances in survey methodology and coverage of health topics. In January 2019, NHIS launched a redesigned content and structure that differs from its previous questionnaire design. Persons excluded from the sample are those with no fixed household address, military personnel, persons in long-term care institutions, persons in correctional facilities, and U.S. nationals living in foreign countries.  Data collection on the NHIS is continuous, i.e., from January to December each year.

[Access data set here](https://www.cdc.gov/nchs/nhis/2019nhis.htm)

**Behavioral Risk Factor Surveillance System (BRFSS)**

The Behavioral Risk Factor Surveillance System (BRFSS) is the nation’s system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world. The basic philosophy was to collect data on actual behaviors, rather than on attitudes or knowledge, that would be especially useful for planning, initiating, supporting, and evaluating health promotion and disease prevention programs. In addition to age, gender, and race/ethnicity, raking permits more demographic variables to be included in weighting such as education attainment, marital status, tenure (property ownership), and telephone ownership. 

[Access data set here](https://www.cdc.gov/brfss/annual_data/annual_2019.html)

**NYC Open Data**

Open Data is an opportunity to engage New Yorkers in the information that is produced and used by City government.   In New York City, access to open data is the law. In 2012, the “Open Data Law,” which amended the New York City administrative code to mandate that all public data be made available on a single web portal by the end of 2018. Since then, there have been several amendments approved to the Open Data Law. These laws, which include stronger requirements on data dictionaries and data retention, response timelines for public requests, and an extension of the Open Data mandate into perpetuity, help make it easier for New Yorkers to access City data online and anchor the city’s transparency initiatives around Open Data.


***New York City Locations Providing Seasonal Flu Vaccinations***

Data provide the location and facility information for places in New York City providing seasonal flu vaccinations. Data were provided by Department of Health and Mental Hygiene (DOHMH)

[Access data set here](https://data.cityofnewyork.us/Health/New-York-City-Locations-Providing-Seasonal-Flu-Vac/w9ei-idxz)

***New York City influenza-like and pneumonia hospital admissions***

Data provide the total emergency department visits, and visits and admissions for influenza-like and/or pneumonia illness by modified ZIP code tabulation area of patient residence.
Data were provided by Department of Health and Mental Hygiene (DOHMH). 


[Access data set here](https://data.cityofnewyork.us/Health/Emergency-Department-Visits-and-Admissions-for-Inf/2nwg-uqyg)


**Twitter**
Using rverst, data were scraped from the website. 

[Access data set here](https://twitter.com)


###	Research setting
###	Data collection methods
###	Measures
###	Analytical methods
###	Ethical concerns and protection of human subjects
