---
title: "Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---


## Introduction

The "abstract" and introduction for the project can be obtained by visiting [here.](index.html)

## Methods

### Overview of research design

### Sources of data

#### National Health Survey

The National Health Interview Survey (NHIS) is one of the major data collection programs of the National Center for Health Statistics (NCHS) which is part of the Centers for Disease Control and Prevention (CDC). While the NHIS has been conducted continuously since 1957, the content of the survey has been updated about every 15-20 years to incorporate advances in survey methodology and coverage of health topics. In January 2019, NHIS launched a redesigned content and structure that differs from its previous questionnaire design. Persons excluded from the sample are those with no fixed household address, military personnel, persons in long-term care institutions, persons in correctional facilities, and U.S. nationals living in foreign countries.  Data collection on the NHIS is continuous, i.e., from January to December each year.

Access data set [here]: https://www.cdc.gov/nchs/nhis/2019nhis.htm

#### Behavioral Risk Factor Surveillance System (BRFSS)

The Behavioral Risk Factor Surveillance System (BRFSS) is the nation’s system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world. The basic philosophy was to collect data on actual behaviors, rather than on attitudes or knowledge, that would be especially useful for planning, initiating, supporting, and evaluating health promotion and disease prevention programs. In addition to age, gender, and race/ethnicity, raking permits more demographic variables to be included in weighting such as education attainment, marital status, tenure (property ownership), and telephone ownership. 

Access data set here: https://www.cdc.gov/brfss/annual_data/annual_2019.html

#### NYC Open Data 

Open Data is an opportunity to engage New Yorkers in the information that is produced and used by City government.   In New York City, access to open data is the law. In 2012, the “Open Data Law,” which amended the New York City administrative code to mandate that all public data be made available on a single web portal by the end of 2018. Since then, there have been several amendments approved to the Open Data Law. These laws, which include stronger requirements on data dictionaries and data retention, response timelines for public requests, and an extension of the Open Data mandate into perpetuity, help make it easier for New Yorkers to access City data online and anchor the city’s transparency initiatives around Open Data.


***New York City Locations Providing Seasonal Flu Vaccinations***

Data provide the location and facility information for places in New York City providing seasonal flu vaccinations. Data were provided by Department of Health and Mental Hygiene (DOHMH)

Access data set here: https://data.cityofnewyork.us/Health/New-York-City-Locations-Providing-Seasonal-Flu-Vac/w9ei-idxz

***New York City influenza-like and pneumonia hospital admissions***

Data provide the total emergency department visits, and visits and admissions for influenza-like and/or pneumonia illness by modified ZIP code tabulation area of patient residence.
Data were provided by Department of Health and Mental Hygiene (DOHMH). 


Access data set here: https://data.cityofnewyork.us/Health/Emergency-Department-Visits-and-Admissions-for-Inf/2nwg-uqyg


#### Twitter
Using rverst, data were scraped from the website. 


###	Overview of research design

#### Our project is based on our research questions: 

- “What are the attitudes of adults regarding the seasonal influenza vaccine?”

- “What trends emerge adults’ seasonal influenza vaccine?”

- “What are the effects that result from adult’s engagement or disengagement with the seasonal influenza vaccine?” 


#### Attitudes structure can be described in terms of three components.

o	**Affective component:** this involves a person’s feelings / emotions about the attitude object. “I hate vaccines”.

o	**Behavioral (or conative) component:** the way the attitude we have influences on how we act or behave. For example: “I will obtain a influenza vaccine once it becomes available”.

o	**Cognitive component:** this involves a person’s belief / knowledge about an attitude object. For example: “I believe vaccines are safe”.

#### Through engagement with the allotted datasets we will begin to understand:

1.	What feelings do adults have regarding flu vaccines?
**Why? This will help us understand how adults might feel in regards to available or theoretical vaccines.**

2.	How do adults behave towards flu vaccines?
**Why? This will help us understand what actions should be encouraged or discontinued in regards to available or theoretical vaccines.**

3.	What do adults know about vaccines?

**Why? This will help us understand gaps in education, misinformation that might be occurring, and where information should be directed towards**

#### Hypothesis - What do we think we will find?

-	The proportion of individuals who receive a flu vaccine will increase over the years
-	There might be a decrease in flu vaccinations due to the Anti-Vaxx movement
-	Communities with lower allocations of resources will have less access to obtain vaccinations
-	Insurance coverage will have a significant association with vaccination status
-	There will be more individuals with polarizing views on vaccines than those with indifferent stances

#### Research aim

Highlights trends in flu vaccine data to ultimately support efforts in research and program implementation, to ensure that all of those eligible to obtain a flu vaccine to get one.  This is in a desire to encourage immunization rates for other communicable disease, especially for the ongoing COVID-19 pandemic. 

###	Research setting

Our study utilizes data composed of a random sample of inhabitants from the United States, as BRFSS and NHS data consists of respondents from all US geographical and social communities.  However, for part of this study, the geographical community is specifically geared towards those in the NYC metro area.  We find this selection to be fitting considering our research question is aimed at understanding the attitudes, associations, and influences surrounding flu vaccination engagement.  This geographic awareness brings us to the current situation unfolding in the United States, that the country is leading the world in having one of the poorest responses to the current COVID-19 pandemic.  Consequently, we found it appropriate to explore any trends that might arise from this area. We are all students of Columbia University’s Mailman School of Public Health.  Attending a graduate institution located in NYC and being residents in the city allows for us to be particularly engaged with the study for its’ apparent relevance.  Dense, metropolitan areas tend to be the most affected during health crisis, lending support to our exploration of data regarding influenza like symptoms.  

### Data collection methods
###	Measures
###	Analytical methods
Analytical methods for the project can be obtained by visiting the page below.

[Statistical information from National Health Survey](stat.html)

###	Ethical concerns and protection of human subjects

IRB approval was not necessary to access the data.  Data from the NHS, BRFSS, and NYC Open Data were de-identified.  Additionally, data scraped from Twitter have been de-identified to protect all human subjects.  


## Results

Results for the project can be obtained by visiting the pages below.

[National Health Survey Results](methods.html)


[Behavioral Risk Factor Surveillance System Results](test_storyboard.html)


**link adam's map**

**link twitter data**
 

## Discussion

Need to answer

Problems we ran into?
Conclusions?
What are the consequences of not engaging with flu shots?
Next steps?
Things to think about?

## Authors

[Adam, Maria, Ronaé](extras.html)
